### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by DataExplorerUser** [motojinc25/WeDX#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
pip install on Win10 with Python 3.9 for the common requirements and the specific requirements for AMD. The IDE is giving the message "No module named 'cv2'.". 

### Any log messages given by the failure
> No.

### Expected/desired behavior
> That the app would start and show the GUI. Right now it quickly flashes and ends without an error message. 

### OS and Version?
> Windows 10, 64 bit

### Mention any other details that might be useful

> ---------------------------------------------------------------
> I'd love to feature WeDX on the [showcase](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase) page of Dear PyGui as it looks great! I'd like to add a little GIF to show it in action. But for now, I'm stuck at getting it to run.

**Comment by motojinc25** [comment]
Thank you for submitting an issue.
What is the WeDX version?
How did you install pip packages? (ex: python -m pip install -r .\requirements\win_amd64.txt)
Could you show the 「pip freeze」 result?

**Comment by DataExplorerUser** [comment]
For now, I think I'm causing the issue as somehow the venv is not set up properly. I have tried cloning the project and downloading the ZIP file with similar results.

I'll reach out again once I figured it out.

**Comment by motojinc25** [comment]
Maybe you have to two Pythons installed and you installed module in one Python but you run code with other Python. In console/terminal check versions python -V and pip -V.

**Comment by DataExplorerUser** [comment]
In the end, my goal is to create a GIF so that I can add WeDX to the [Dear PyGui showcase](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase). Would you be willing to create such a GIF yourself? Basically like the [screenshot on your readme](https://github.com/motojinc25/WeDX/blob/main/docs/assets/images/wedx_0.10.0.png), but with a bit of action and movement, so the user can see what's happening. You could upload to your repository and I could link it. For free GitHub accounts, I believe it should be below 7 or 8 Mb in size.

I have uninstalled the project for now, so I cannot check versions at the moment.

**Comment by motojinc25** [comment]
I created an animation GIF and added it to the repository.
Link information.
https://github.com/motojinc25/WeDX/raw/main/docs/assets/images/wedx_0.10.0.gif

**Comment by DataExplorerUser** [comment]
Thank you, much appreciated. I have added it to the [showcase](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase#wedx). 

I don't quite know how to describe the application, so if you could write a couple of sentences about what it is or does, that would be great! 👍

**Comment by motojinc25** [comment]
How about this?
---
[WeDX](https://github.com/motojinc25/WeDX/) is an open-source utility toolkit that defines a pipeline by expressing the flow of data (video and message) with three types of nodes and lines: source, processor, and sink, in order to quickly realize Edge AI. Pipeline handling can be operated by integrating with [Azure IoT](https://azure.microsoft.com/en-us/solutions/iot/) (Azure IoT Hub, Azure IoT Hub DPS, Azure IoT Central) other than locally, so it can be used as a [PoC](https://en.wikipedia.org/wiki/Proof_of_concept) for business scenarios. Recently, we have also integrated [Flask](https://flask.palletsprojects.com/) and [Streamlit](https://streamlit.io/) to work with web apps.
It supports x64 Windows, macOS, Linux, and ARM (arm64v8) Linux container without GUI.

**Comment by DataExplorerUser** [comment]
Thank you! That's already pretty good, but it's not clear to me what Edge AI means. 

And what is the aim of the pipeline? To transform images? To apply object recognition? 

For the purpose of the showcase, I'm not to concerned with the details of Azure services, but more what added value the tool can provide to users in more generic terms.

**Comment by motojinc25** [comment]
Thank you! I understand the your advice you gave. How's this?

---
WeDX is an open-source utility with Python and Dear PyGui. The app provides you a platform for building intelligent video applications that span the edge and the cloud. Combining many features of Dear PyGui, it offers the capability to capture, record, and analyze videos and publish the results, namely video and insights from video, to edge or cloud.

**Comment by DataExplorerUser** [comment]
Thank you. That makes more sense to me. What does edge mean? Is that your own local machine?

Does the app transform the video in any way? Or put another way, what's the value of the node editor?

**Comment by motojinc25** [comment]
Yes, edge means it is processed locally on an individual devices and is also called edge computing.

The value is that you can define a flow with no-code while checking in real time so that you can combine the three types of nodes (source, processor, and sink) in the Node Editor, infer the video source with the AI model, and provide the result to the service or application.

**Comment by motojinc25** [comment]
This issue will be closed.
